import naive from 'naive-ui';
import { createApp, Vue } from 'vue';
import App from './App.vue';
import router from './router';
import './assets/tailwind.css';
import { createPinia } from 'pinia';
import ErrorHandler from './util/errorHandler';
let app = createApp(App).use(createPinia()).use(naive).use(router);
app.config.errorHandler = ErrorHandler;
app.mount('#app');
